apiVersion: v1
kind: Namespace
metadata:
  name: fluxcd-tf-packageinstalls
---
apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-tf-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-installs
  namespace: fluxcd-tf-packageinstalls
  annotations: 
    kapp.k14s.io/change-group: flux-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluxcd-tf-packageinstall
  annotations: 
    kapp.k14s.io/change-group: flux-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzupackage-install-admin-role
subjects:
- kind: ServiceAccount
  name: flux-installs
  namespace: fluxcd-tf-packageinstalls