---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-install-cluster-admin-role
  annotations: 
    kapp.k14s.io/change-group: external-dns-serviceaccount
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-install-cluster-admin-role-binding
  annotations: 
    kapp.k14s.io/change-group: external-dns-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-install-cluster-admin-role
subjects:
- kind: ServiceAccount
  name: external-dns-install-sa
  namespace: external-dns-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-install-sa
  namespace: external-dns-install
  annotations: 
    kapp.k14s.io/change-group: external-dns-serviceaccount
