#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-accelerators
  namespace: tap-accelerators
  annotations:
    kapp.k14s.io/change-rule.serviceaccount-del: "delete before deleting tap-accelerators-serviceaccount"
    kapp.k14s.io/change-rule.external-dns-upsert: "upsert after upserting tap"
spec:
  serviceAccountName: tap-accelerators
  fetch:
  - git:
      url: #@ data.values.gitops.repo
      ref: #@ data.values.gitops.ref
      subPath: accelerators
  template:
  - ytt: {}
  deploy:
  - kapp: {}
