apiVersion: v1
kind: Namespace
metadata:
  name: tap-accelerators
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-accelerators
  namespace: tap-accelerators
  annotations: 
    kapp.k14s.io/change-group: tap-accelerators-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tap-accelerators-serviceaccount-binding
  annotations: 
    kapp.k14s.io/change-group: tap-accelerators-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzupackage-install-admin-role
subjects:
- kind: ServiceAccount
  name: tap-accelerators
  namespace: tap-accelerators